name: JumpPadPlugin
main: se.fredsfursten.jumppadplugin.JumpPadPlugin
version: 1.2.1
author: vanbrayne
description: A Minecraft plugin for so called "Jump Pad" functionality
commands:
  jumppad:
    description: Control jump pads
    usage: /jumppad add| remove | edit | goto | list 
    permission-message: You don't have <permission>
permissions:
  jumppad.*:
    description: Gives access to all jumppad commands
    default: op
    jumppad.add: true
    jumppad.remove: true
    jumppad.edit: true
    jumppad.list: true
    jumppad.goto: true
  jumppad.add:
    description: Access to /jumppad add command
    default: op
  jumppad.remove:
    description: Access to /jumppad remove command
    default: op
  jumppad.edit:
    description: Access to /jumppad edit command
    default: op
  jumppad.list:
    description: Access to /jumppad list command
    default: op
  jumppad.goto:
    description: Access to /jumppad goto command
    default: op
  jumppad.jump:
    description: Can jump from a jumppad
    default: op
