name: JumpPadPlugin
main: se.fredsfursten.jumppadplugin.JumpPadPlugin
version: 0.1
author: vanbrayne
description: A Minecraft plugin for so called "Jump Pad" functionality
commands:
  jumppad:
    description: Control jump pads
    usage: /jumppad add [up speed] [forward speed] | remove
    permission: jumppad.activate
    permission-message: You don't have <permission>
permissions:
  jumppad.*:
    description: Gives access to all jumppad commands
    default: op
    jumppad.add: true
    jumppad.remove: true
  jumppad.add:
    description: Access to /jumppad add command
    default: op
  jumppad.remove:
    description: Access to /jumppad remove command
    default: op
  jumppad.jump:
    description: Can jump from a jumppad
    default: op
